### PR TITLE
Disable diff output so travis logs don't get too long.

### PR DESCRIPTION
**Pull request by patcon**
Tests are failing, but I can't see the end of the run easily :)

### CODE REVIEW

**Comment by patcon** [comment]
Hm. Breakage might coincide with test-kitchen 1.5 release. I'll try that too in this PR

**Comment by patcon** [comment]
Rats. Ok, the version pinning didn't work. Any intuition on what might have changed @legal90?

**Comment by legal90** [comment]
@patcon I've fixed it by #98

**Comment by patcon** [comment]
Hey @legal90, just a minor thing, but in the name of open source etiquette, the `--author` tag is a thing for attribution :)

I've got an alias in my git file for just such situations when it's easier to subsume someone else's changes into my own branch. Feed it a previous commit and it spits out the author ref:

``` ini
[alias]
  email = !git --no-pager show -s --format='%aN <%aE>'
```

**Pull request closed without merging**
