### PR TITLE
Gh 14 and 21

### LINKED ISSUE #14: InnoDB and max_allowed_packet not set for MySQL
According to [Database Setup For MySQL Documentation Page, Step 3](https://confluence.atlassian.com/display/CONF55/Database+Setup+For+MySQL#DatabaseSetupForMySQL-Step3.ConfigureMySQLServer), point 2, Set the default storage engine should be set to `InnoDB` and `max_allowed_packet` value should be at least `32M`:

```
[mysqld]
...
default-storage-engine=INNODB
max_allowed_packet=32M
...
```

I actually remember having problems in prod because of the later.

### LINKED ISSUE #21: MySQL server's default character set not set to UTF8
This issue is close to issue #14.

According to [Database Setup For MySQL Documentation Page, Step 3](https://confluence.atlassian.com/display/CONF55/Database+Setup+For+MySQL#DatabaseSetupForMySQL-Step3.ConfigureMySQLServer), point 2, the default character set for the MySQL server should be set to `utf8` as following and is not :

```
[mysqld]
...
character-set-server=utf8
collation-server=utf8_bin
...
```

### PR DESCRIPTION
**Pull request by esciara**
Fixes #14 and fixes #21

### CODE REVIEW

**Comment by esciara** [comment]
@bflad : same as https://github.com/bflad/chef-confluence/pull/19#issuecomment-68716549. Build failure not due to my code.

**Comment by legal90** [comment]
@bflad, Any updates on this?

**Comment by patcon** [comment]
This seems outdated now. Anyone interested in investigating whether it still applies and updating it, or should be close it out? (I'll give it a week for reply, then close out)

**Comment by legal90** [comment]
Thank you for contribution! But I close this PR merge conflicts caused by the huge changes done here since the previous release. 
It should be rebased.

**Pull request closed without merging**
