### PR TITLE
Support for newer versions of Confluence

### PR DESCRIPTION
**Pull request by legal90**
Added support of Confluence 5.5.2, 5.5.3, 5.6, 5.6.1, 5.6.3, 5.7

@esciara I've rebased a couple of your commits here, OK?

### CODE REVIEW

**Comment by esciara** [comment]
@legal90 yep it is OK.
 It looks like this repo is not maintained any more. Cannot take on myself to make a maintained fork unfortunately :-/  Have you looked at other forks ? (https://github.com/bflad/chef-confluence/network) I did quite a bit of work on mine (https://github.com/esciara/chef-confluence/). and the one from https://github.com/QVCItalia/chef-confluence looks interesting too...

**Comment by bflad** [comment]
Does either of you want merge permissions for this repo?

**Comment by legal90** [comment]
@bflad Yes, it would be great.

**Comment by esciara** [comment]
@bflad yep would be great

**Comment by ringods** [comment]
@bflad are there more people with merge permissions already? I work for an Atlassian partner in Belgium and I can help maintain chef-jira, chef-confluence, chef-stash, etc.

**Comment by legal90** [comment]
@bflad any updates?

**Comment by legal90** [comment]
@bflad Please, let's do something with that. Your cookbooks for Atlassian products are really useful, but too outdated. If you are not able to support them, please, let community to contribute.

P.s. Supermarket site also supports collaboration and ownership transfer.

**Pull request merged**
