### PR TITLE
Add workaround for https://jira.atlassian.com/browse/CONF-35722

### PR DESCRIPTION
**Pull request by mvdkleijn**
@legal90 - I know you're aware of the issue I'm referring to. :smile:

I'd like to suggest this practical workaround. What do you think?

### CODE REVIEW

**Comment by mvdkleijn** [comment]
note: we want to allow disabling backups on update due to them causing issues for some people

cc: @ojawel

**Comment by legal90** [comment]
@mvdkleijn Thanks! But I don't work at Parallels any longer, so let it be up to @anuriq, who is a cookbook maintainer at the moment.

In my personal opinion, I would move to `standalone` installation type for production.

**Comment by anuriq** [comment]
@mvdkleijn Hi! Have you seen CI errors?

**Comment by mvdkleijn** [comment]
@legal90 Cool, good luck at your new place. :smile: I get what you're saying about the `standalone` installation type and probably agree but we're in the middle of a bunch of other changes that take prio.

@anuriq Hi there, sorry about the CI errors! Forgot to check for existence of the file, which is now fixed. CI checks are all green now.

Any chance of getting this into a point release? :smile:

**Pull request merged**
