### PR TITLE
Added new version checksums (5.10.4, 5.10.5, 5.10.6, 5.10.7, 5.10.8, 6.0.1)

### PR DESCRIPTION
**Pull request by katbyte**

### CODE REVIEW

**Comment by mrjcleaver** [comment]
Is this or 6.0 in the works?

**Comment by katbyte** [comment]
I added 6.0 internally already, will push it tonight

**Comment by katbyte** [comment]
@mrjcleaver pushed 6.0.1

**Comment by legal90** [comment]
Thanks! I've fixed the indentation, so now builds are passed fine.

**Pull request merged**
