### PR TITLE
fixes #18

### LINKED ISSUE #18: Chef::Exceptions::RecipeNotFound
Two problems appeared recently:

```
================================================================================
Recipe Compile Error
================================================================================


Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe server for cookbook mysql
```

and

```
================================================================================
Recipe Compile Error
================================================================================


Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe server for cookbook mysql-chef_gem
```

This is due to the fact that
- the [v6 onwards of the mysql cookbook](https://github.com/opscode-cookbooks/mysql/blob/master/CHANGELOG.md#v600-2014-12-15) is now using LWRP and does not have recipes anymore.
- the [mysql-chef_gem cookbook](https://supermarket.chef.io/cookbooks/mysql-chef_gem), which is used in https://github.com/opscode-cookbooks/database, has had some major changes in version 1.0.0 . The [v2.3.1 of the database cookbook](https://github.com/opscode-cookbooks/database/blob/master/CHANGELOG.md#v231-2014-12-13) fixes this. However, I had to delete the `Berksfile.lock` file before running a `berks install` so that v2.3.1 is actually installed.

So to summarise, solution is to:
- lock the cookbook versions in `metadata.rb`:

``` ruby
%w(apache2 mysql_connector postgresql).each do |cb|
  depends cb
end

depends 'database', '~> 2.3'
depends 'mysql', '~> 5.0' 
```
- delete the `Berksfile.lock`
- run `berks install`

### PR DESCRIPTION
**Pull request by esciara**

### CODE REVIEW

**Comment by esciara** [comment]
@bflad : will not fix the Travis build failure as it is not due to my code but to the fact the RuboCop version are not restricted enough in `Gemfile`, hence build is not stable. This build failure should be treated as a separate issue. I have sorted this out in my own code (see commits from 52e09c0744d8adbfc1e03c6ff9247b25ee518ca0 to 3e74feff9f213c28552a9955a93a4c311801494e)

**Comment by esciara** [comment]
Closed by mistake.

**Comment by legal90** [comment]
@bflad Could you please merge it?

**Comment by legal90** [comment]
@esciara Thanks! Merged

**Pull request merged**
