### PR TITLE
Push releases to supermarket

### PR DESCRIPTION
**Pull request by patcon**
Hey @legal90, any chance you might be able to push the current releases to supermarket, or allow me push access to do it on your behalf? Thanks! :)

https://supermarket.chef.io/cookbooks/confluence

cc: @bflad

### CODE REVIEW

**Comment by patcon** [comment]
@bflad bump

**Comment by patcon** [comment]
Added the previously tagged versions to the community site:
https://supermarket.chef.io/cookbooks/confluence

Also converted this to a PR for release support via stove gem.

**Comment by patcon** [comment]
OK, so it seems that at some point, someone tagged and pushed a 1.8.0 release that was not a real release, and it stayed tagged in git. I accidentally also created a community release version for it.

There is a way to delete/yank a cookbook version from the community site via API, but I've confirmed that only the owner (@legal90) can use these methods, not contributors. I've added a command to stove that should allow you to pull the offending 1.8.0 version once the PR is merged or if you install stove from my github branch:

https://github.com/sethvargo/stove/pull/86

```
stove yank confluence 1.8.0
```

Let me know if you're comfortable doing that @legal90

**Comment by legal90** [comment]
Uh... Seems like 1.8.0 tag has been placed on the custom branch, which was not merged to master.
I'll try to remove this release from supermarket.

**Comment by patcon** [comment]
Thanks @legal90! :)

**Comment by legal90** [comment]
@patcon Done. 1.8.0 release has been "yunked"

@bflad Could you please provide @patcon contributor permissions? 
By the way, we will be also glad [to adopt](https://help.github.com/articles/transferring-a-repository/) this repo to https://github.com/parallels-cookbooks/ organization, if you don't have enough time to maintain it. Of course, license type and copyrights will be kept unchanged.

**Comment by legal90** [comment]
@patcon About this pull-request: It looks good, and this stove-related instructions are useful, but... I doubt that anybody else except cookbook maintainers are actually need this. Don't you think so?

**Comment by patcon** [comment]
True, but still good to document, as maintainership can sometime drift and processes risk being forgotten ;)

**Comment by patcon** [comment]
One last thing -- if we can suppress the sense of it being totally bad git mojo, it would be nice to delete the tag as well:

```
git tag -d 1.8.0
git push --delete origin 1.8.0
```

the tag is actually on an orphan commit which exists on _no branch_ fwiw

```
~/repos/chef-confluence (master ✔) ᐅ git branch --contains 1.7.1
* master
~/repos/chef-confluence (master ✔) ᐅ git branch --contains 1.8.0
~/repos/chef-confluence (master ✔) ᐅ 
```

**Comment by legal90** [comment]
@patcon 

> True, but still good to document, as maintainership can sometime drift and processes risk being forgotten 

Ok, let it be :)

>  it would be nice to delete the tag as well:

Probably, there was some failure with that git tag, but even so it is not a good idea to remove it from repository - it was pushed long time ago and somebody can refer to it in their Berksfiles. 
So, we won't release it on the supermarket and can consider version 1.8.0 as unsupported, but I think we have to keep tag in the repo.

**Comment by bflad** [comment]
Ugh so sorry for the delay. @patcon now has contributor access on this repository. Keep making awesomeness. If you'd really like to transfer it to parallels-cookbooks, let me know.

**Comment by patcon** [comment]
Thanks so much @bflad!

**Comment by patcon** [comment]
Deleted orphan `1.8.0` tag from repo as discussed.

**Comment by patcon** [comment]
@legal90 would you have any objection to me peeling off a `2.0.0` release right now? To explain, I humbly suggest there's no need to make a big deal of major releases -- it's just that we should tag a release for supermarket, and it happens that there are breaking changes... so a major bump is simply what it is :)

**Comment by legal90** [comment]
@bflad Thanks!

> If you'd really like to transfer it to parallels-cookbooks, let me know.

Yes, it would be great.

@patcon Before releasing a v2.0.0, I'd like to complete these tasks:
- [ ] Fix unit-test failures
- [ ] Fix #63 - add asserts for attribute `node['mysql']['server_root_password']`
- [ ] Port this change set from jira cookbook: #29
- [x] Port this change set from jira cookbook: #30

**Comment by bflad** [comment]
Hey @legal90 since I don't have admin rights on parallels-cookbooks, I cannot transfer it directly, but I'm going to transfer it to you now.

**Comment by bflad** [comment]
Ha. Can't transfer it until you delete your fork. :)

**Comment by legal90** [comment]
@bflad I've just fixed that. Please, try again to transfer it to me.

**Comment by bflad** [comment]
Hmm. Now Github is saying "legal90 already has a repository in the bflad/chef-confluence network"

**Comment by legal90** [comment]
Ah, seems like fork rename doesn't solve that. Now I've removed it completely. Please, try again.

**Comment by bflad** [comment]
Thanks for adopting this repo @legal90

**Comment by legal90** [comment]
@bflad Thank you too! :+1: 
You are always welcome to contribute to the cookbook as before :)

**Comment by patcon** [comment]
Can I merge this, or should I close it? The title issue title is misleading, as this just adds "stove" support for releasing, and we can merge that without releasing

**Comment by patcon** [comment]
This issue is much too convoluted, so closing.

**Pull request closed without merging**
